config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  mount Shoppe::Engine => "/admin"

  get "category/:id", to: "products#category", as: "product_category"
  get "product/:permalink", to: "products#show", as: "product"
  post "product/:permalink", to: "products#buy", as: "buy"
  get "cart", to: "orders#show"
  get "quick", to: "orders#quick"
  resources :products
  root to: "pages#home"
  get "faqs", to: "pages#faq"
  delete "cart", to: "orders#destroy"
  match "quick_checkout", to: "orders#quick_checkout", as: "quick_checkout", via: [:post]
  match "checkout", to: "orders#checkout", as: "checkout", via: [:get, :patch]
  match "checkout/pay", to: "orders#payment", as: "checkout_payment", via: [:get, :post]
  match "checkout/confirm", to: "orders#confirmation", as: "checkout_confirmation", via: [:get, :post]
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	def destroy
		current_order.destroy
		session[:order_id] = nil
		redirect_to root_path, :notice => "Basket emptied successfully."
	end

  def quick_checkout
    params[:order][:product].each do |product_id, quantity|
      current_order.order_items.add_item(Shoppe::Product.find(product_id), quantity.to_i)
    end

    current_order.proceed_to_confirm(params[:order].permit(:first_name, :last_name, :billing_address1, :billing_address2, :billing_address3, :billing_address4, :billing_country_id, :billing_postcode, :email_address, :phone_number))
    current_order.confirm!
    session[:order_id] = nil
    redirect_to root_path, :notice => "Order has been placed successfully!"
  end

  def checkout
    @order = Shoppe::Order.find(current_order.id)
    if request.patch?
      if @order.proceed_to_confirm(params[:order].permit(:first_name, :last_name, :billing_address1, :billing_address2, :billing_address3, :billing_address4, :billing_country_id, :billing_postcode, :email_address, :phone_number))
      redirect_to checkout_confirmation_path
      end
    end
  end

  def payment
    if request.post?
      redirect_to checkout_confirmation_path
    end
  end

  def confirmation
    if request.post?
      # Shoppe::OrderMailer.accepted(@order).deliver
      current_order.confirm!
      session[:order_id] = nil
      redirect_to root_path, :notice => "Order has been placed successfully!"
    end
  end

  def quick
    @products = Shoppe::Product.root.ordered.includes(:product_categories, :variants)
    @products = @products.group_by(&:product_category)
    # @parent_categories = Shoppe::ProductCategory.where(parent_id: nil)
    # @products = Shoppe::Product.all
    @order = current_order
  end

end

# class OrdersController < ApplicationController
  
#   before_filter(:except => :status) { redirect_to root_path unless has_order? }
  
#   def status
#     @order = Shoppe::Order.find_by_token!(params[:token])
#   end
  
#   def destroy
#     current_order.destroy
#     session[:order_id] = nil
#     respond_to do |wants|
#       wants.html { redirect_to root_path, :notice => "Your basket has been emptied successfully."}
#       wants.json do
#         flash[:notice] = "Your shopping bag is now empty."
#         render :json => {:status => 'complete', :redirect => root_path}
#       end
#     end
#   end
  
#   def remove_item
#     item = current_order.order_items.find(params[:order_item_id])
#     if current_order.order_items.count == 1
#       destroy
#     else
#       item.remove
#       respond_to do |wants|
#         wants.html { redirect_to request.referer, :notice => "Item has been removed from your basket successfully"}
#         wants.json do
#           current_order.reload
#           render :json => {:status => 'complete', :items => render_to_string(:partial => 'shared/order_items.html', :locals => {:order => current_order})}
#         end
#       end
#     end
#   end
  
#   def change_item_quantity
#     item = current_order.order_items.find(params[:order_item_id])
#     request.delete? ? item.decrease! : item.increase!
#     respond_to do |wants|
#       wants.html { redirect_to request.referer || root_path, :notice => "Quantity has been updated successfully." }
#       wants.json do
#         current_order.reload
#         if current_order.empty?
#           destroy
#         else
#           render :json => {:status => 'complete', :items => render_to_string(:partial => 'shared/order_items.html', :locals => {:order => current_order})}
#         end
#       end
#     end    
#   rescue Shoppe::Errors::NotEnoughStock => e
#     respond_to do |wants|
#       wants.html { redirect_to request.referer, :alert => "Unfortunately, we don't have enough stock. We only have #{e.available_stock} items available at the moment. Please get in touch though, we're always receiving new stock." }
#       wants.json { render :json => {:status => 'error', :message => "Unfortunateley, we don't have enough stock to add more items."} }
#     end
#   end

#   def change_delivery_service
#     if current_order.delivery_service = current_order.available_delivery_services.select { |s| s.id == params[:delivery_service].to_i}.first
#       current_order.save
#       respond_to do |wants|
#         wants.html { redirect_to request.referer, :notice => "Delivery service has been changed"}
#         wants.json do
#           current_order.reload
#           render :json => {:status => 'complete', :items => render_to_string(:partial => 'shared/order_items.html', :locals => {:order => current_order})}
#         end
#       end
#     else
#       respond_to do |wants|
#         wants.html { redirect_to request.referer, :alert => "You cannot select this delivery method."}
#         wants.json { render :json => {:status => 'error', :message => 'InvalidDeliveryMethod'}, :status => 422 }
#       end
#     end
#   end
  
#   def checkout
#     @order = Shoppe::Order.find(current_order.id)
    
    
#     if request.patch?
#       @order.attributes = params[:order].permit(:first_name, :last_name, :company, :billing_address1, :billing_address2, :billing_address3, :billing_address4, :billing_country_id, :billing_postcode, :email_address, :phone_number, :delivery_name, :delivery_address1, :delivery_address2, :delivery_address3, :delivery_address4, :delivery_postcode, :delivery_country_id, :separate_delivery_address)
#       @order.ip_address = request.ip
#       if @order.proceed_to_confirm
#         # redirect_to checkout_payment_path
#         redirect_to checkout_confirmation_path
#       end
#     # else
#     #   # Add some example order data for the example. In a real application
#     #   # this shouldn't be present.
#     #   Faker::Config.locale = 'en-GB'
#     #   @order.first_name = Faker::Name.first_name                                            if @order.first_name.blank?
#     #   @order.last_name = Faker::Name.last_name                                              if @order.last_name.blank?
#     #   @order.company = Faker::Company.name                                                  if @order.company.blank?
#     #   @order.email_address = Faker::Internet.email                                          if @order.email_address.blank?
#     #   @order.phone_number = Faker::PhoneNumber.phone_number                                 if @order.phone_number.blank?
#     #   @order.billing_address1 = Faker::Address.building_number + " " + Faker::Address.street_name   if @order.billing_address1.blank?
#     #   @order.billing_address3 = Faker::Address.city                                                 if @order.billing_address3.blank?
#     #   @order.billing_address4 = Faker::Address.country                                               if @order.billing_address4.blank?
#     #   @order.billing_postcode = Faker::Address.zip                                                  if @order.billing_postcode.blank?
#     # end
#     end
#   end
  
#   def payment
#     @order = Shoppe::Order.find(current_order.id)
#     if request.patch?
#       redirect_to checkout_confirmation_path
#     end
#   end
  
#   def confirmation
#     unless current_order.confirming?
#       # redirect_to checkout_path
#       redirect_to root_path
#       return
#     end
    
#     if request.patch?
#       begin
#         current_order.confirm!
#         # This payment method should usually be called in a payment module or elsewhere but for the demo
#         # we are adding a payment to the order straight away.
#         current_order.payments.create(:method => "Credit Card", :amount => current_order.total, :reference => rand(10000) + 10000, :refundable => true)
#         session[:order_id] = nil
#         redirect_to root_path, :notice => "Order has been placed!"
#       # rescue Shoppe::Errors::PaymentDeclined => e
#       #   flash[:alert] = "Payment was declined by the bank. #{e.message}"
#       #   redirect_to checkout_path
#       # rescue Shoppe::Errors::InsufficientStockToFulfil
#       #   flash[:alert] = "We're terribly sorry but while you were checking out we ran out of stock of some of the items in your basket. Your basket has been updated with the maximum we can currently supply. If you wish to continue just use the button below."
#       #   redirect_to checkout_path
#       # end
#     end
#   end
# end
# end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for @order, :url => quick_checkout_path, method: :post do |f| %>
  <dl>
	<% @products.each do |category, products| %>
	  <h3><%= category.name %></h3>
	  <ul>
	    <% products.each do |product| %>
	    <li>
	      <h4><%= product.name %></h4>
	      <p><%= product.short_description %></p>
	      <p><b>Price:</b> <%= number_to_currency product.price %></p>
	      Quantity: <input name="order[product][<%= product.id %>]">
	    </li>
	    <% end %>
	  </ul>
	<% end %>
  </dl>
  <dl>
    <dt><%= f.label :first_name, 'Name' %></dt>
    <dd><%= f.text_field :first_name %> <%= f.text_field :last_name %></dd>

    <dt><%= f.label :billing_address1, 'Address' %></dt>
    <dd><%= f.text_field :billing_address1 %></dd>
    <dd><%= f.text_field :billing_address2 %></dd>
    <dd><%= f.text_field :billing_address3 %></dd>
    <dd><%= f.text_field :billing_address4 %></dd>
    <dt><%= f.label :billing_postcode, 'Post code' %></dt>
    <dd><%= f.text_field :billing_postcode %></dd>
    <dd><%= f.collection_select :billing_country_id, Shoppe::Country.ordered, :id, :name, :include_blank => true %></dd>

    <dt><%= f.label :email_address %></dt>
    <dd><%= f.text_field :email_address %></dd>

    <dt><%= f.label :phone_number %></dt>
    <dd><%= f.text_field :phone_number %></dd>

    <dd><%= f.submit 'Continue' %></dd>
  </dl>

  <br><br>
<% end %>

app/views/orders/_items.html.erb
<table width='100%' border='1'>
  <thead>
    <tr>
      <td>Quantity</td>
      <td>Product</td>
      <td>Sub-Total</td>
      <!-- <td>Tax</td> -->
      <td>Total</td>
    </tr>
  </thead>
  <tbody>
    <% order.order_items.each do |item| %>
    <tr>
      <td><%= item.quantity %></td>
      <td><%= item.ordered_item.full_name %></td>
      <td><%= number_to_currency item.sub_total %></td>
      <!-- <td><%= number_to_currency item.tax_amount %></td> -->
      <td><%= number_to_currency item.total %></td>
    </tr>
    <% end %>

    <% if order.delivery_service %>
    <tr>
      <td></td>
      <td><%= order.delivery_service.name %></td>
      <td><%= number_to_currency order.delivery_price %></td>
      <!-- <td><%= number_to_currency order.delivery_tax_amount %></td> -->
      <td><%= number_to_currency order.delivery_price + order.delivery_tax_amount %></td>
    </tr>
    <% end %>

  </tbody>
  <tfoot>
    <tr>
      <td colspan='3'>Sub-Total</td>
      <td><%= number_to_currency order.total_before_tax %></td>
    </tr>
    <!-- <tr>
      <td colspan='4'>Tax</td>
      <td><%= number_to_currency order.tax %></td>
    </tr> -->
    <tr>
      <td colspan='3'>Total</td>
      <td><%= number_to_currency order.total %></td>
    </tr>
  </tfoot>
</table>

app/views/orders/checkout.html.erb
<section id="products">

<h2>Checkout</h2>
<%= render 'items', :order => @order %>

<%= form_for @order, :url => checkout_path do |f| %>
  <dl>
    <dt><%= f.label :first_name, 'Name' %></dt>
    <dd><%= f.text_field :first_name %> <%= f.text_field :last_name %></dd>

    <dt><%= f.label :billing_address1, 'Address' %></dt>
    <dd><%= f.text_field :billing_address1 %></dd>
    <dd><%= f.text_field :billing_address2 %></dd>
    <dd><%= f.text_field :billing_address3 %></dd>
    <dd><%= f.text_field :billing_address4 %></dd>
    <dt><%= f.label :billing_postcode, 'Post code' %></dt>
    <dd><%= f.text_field :billing_postcode %></dd>
    <dd><%= f.collection_select :billing_country_id, Shoppe::Country.ordered, :id, :name, :include_blank => true %></dd>

    <dt><%= f.label :email_address %></dt>
    <dd><%= f.text_field :email_address %></dd>

    <dt><%= f.label :phone_number %></dt>
    <dd><%= f.text_field :phone_number %></dd>

    <dd><%= f.submit 'Continue' %></dd>
  </dl>
<% end %>

</section>

app/views/orders/confirmation.html.erb
<section id="products">

<h2>Place your order</h2>
<%= render 'items', :order => current_order %>
<br>
<%= button_to "Place order" %>

</section>

app/views/orders/payment.html.erb
<h2>Make your payment</h2>
<%= form_tag do %>
  <dl>
    <dt><%= label_tag 'card_number' %></dt>
    <dd><%= text_field_tag 'card_number' %></dd>
    <dt><%= label_tag 'expiry' %></dt>
    <dd><%= text_field_tag 'expiry' %></dd>
    <dt><%= label_tag 'security_code' %></dt>
    <dd><%= text_field_tag 'security_code' %></dd>
    <dd><%= submit_tag "Continue" %></dd>
  </dl>
<% end %>

app/views/orders/quick.html.erb
<section id="products">
<h1>Quick Buy Form</h1>
	<%= render "form" %>

</section>

app/views/orders/show.html.erb
<section id="products">

<h2>Your basket</h2>
<%= render 'items', :order => current_order %>
<br>
<p><%= link_to 'Empty basket', cart_path, :method => :delete %></p>

</section>