config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  mount Shoppe::Engine => "/admin"

  get "category/:id", to: "products#category", as: "product_category"
  get "product/:permalink", to: "products#show", as: "product"
  post "product/:permalink", to: "products#buy", as: "buy"
  get "cart", to: "orders#show"
  get "quick", to: "orders#quick"
  resources :products
  root to: "pages#home"
  get "faqs", to: "pages#faq"
  delete "cart", to: "orders#destroy"
  match "quick_checkout", to: "orders#quick_checkout", as: "quick_checkout", via: [:post]
  match "checkout", to: "orders#checkout", as: "checkout", via: [:get, :patch]
  match "checkout/pay", to: "orders#payment", as: "checkout_payment", via: [:get, :post]
  match "checkout/confirm", to: "orders#confirmation", as: "checkout_confirmation", via: [:get, :post]
end

app/controllers/products_controller.rb
# class ProductsController < ApplicationController

#   def index
#     @products = Shoppe::Product.root.ordered.includes(:product_categories, :variants)
#     @products = @products.group_by(&:product_category)
#   end

#   def show
#     @product = Shoppe::Product.root.find_by_permalink(params[:permalink])
#   end

#   def buy
#   	@product = Shoppe::Product.root.find_by_permalink!(params[:permalink])
#   	current_order.order_items.add_item(@product, 1)
#   	redirect_to product_path(@product.permalink), :notice => "Product has been added successfuly!"
#   end

# end


class ProductsController < ApplicationController

  before_action :authenticate_customer!
  
  before_filter do
    if params[:category_id]
      @product_category = Shoppe::ProductCategory.where(:permalink => params[:category_id]).first!
    end
    if @product_category && params[:product_id]
      @product = @product_category.products.where(:permalink => params[:product_id]).active.first!      
    end
  end
  
  # def index
  #   @products = @product_category.products.includes(:product_categories, :variants).root.active
  # end

  def index
    # @products = Shoppe::Product.root.ordered.includes(:product_categories, :variants)
    # @products = @products.group_by(&:product_category)
    @parent_categories = Shoppe::ProductCategory.where(parent_id: nil)
  end
  
  def filter
    @products = Shoppe::Product.active.with_attributes(params[:key].to_s, params[:value].to_s)
  end
  
  def categories
    @product_categories = Shoppe::ProductCategory.ordered
  end
  
  def show
    # @product = @product.product_attributes.public.to_a
    @product = Shoppe::Product.root.find_by_permalink(params[:permalink])
  end
  
  def add_to_basket
    product_to_order = params[:variant] ? @product.variants.find(params[:variant].to_i) : @product
    current_order.order_items.add_item(product_to_order, params[:quantity].blank? ? 1 : params[:quantity].to_i)
    respond_to do |wants|
      wants.html { redirect_to request.referer }
      wants.json { render :json => {:added => true} }
    end
  rescue Shoppe::Errors::NotEnoughStock => e
    respond_to do |wants|
      wants.html { redirect_to request.referer, :alert => "We're sorry but we don't have enough stock to add that many products. We currently have #{e.available_stock} item(s) in stock. Please try again."}
      wants.json { render :json => {:error => 'NotEnoughStock', :available_stock => e.available_stock}}
    end
  end


  def buy
    @product = Shoppe::Product.root.find_by_permalink!(params[:permalink])
    current_order.order_items.add_item(@product,1)
    redirect_to product_path(@product.permalink), :notice => "Product has been added successfully!"
  end

  def category
    # @products = Shoppe::ProductCategory.where(id: params[:id])
    # Shoppe::Product.root.ordered.includes(:product_categories, :variants)
    @products = Shoppe::Product.root.ordered.includes(:product_categories).where("shoppe_product_categories.id = #{params[:id]}")
  end
  
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/category.html.erb
<section id="products">
<h2>Products</h2>

<% @products.each do |product| %>
  
  <ul>

    <li>
      <h4><%= link_to product.name, product_path(product.permalink) %></h4>
      <p><%= product.short_description %></p>
      <p><b>Price:</b> <%= number_to_currency product.price %></p>
    </li>

  </ul>
<% end %>

</section>

app/views/products/index.html.erb
<section id="products">
<h2>Products</h2>


<% @parent_categories.each do |category| %>
  <h3><%= category.name %></h3>
  <% Shoppe::ProductCategory.where(parent_id: category.id).each do |c| %>
    <%= link_to c.name, product_category_path(c) %><br>
  <% end %>
  
<% end %>


</section>

app/views/products/show.html.erb
<section id="products">

<h2><%= @product.name %></h2>

<% if @product.default_image %>
  <%= image_tag @product.default_image.path, :width => '200px', :style => "float:right" %>
<% end %>

<p><%= @product.short_description %></p>
<p>
  <b><%= number_to_currency @product.price %></b>
  <%= link_to "Add to basket", product_path(@product.permalink), :method => :post %>
</p>

<hr>
<%= simple_format @product.description %>
<hr>

<p><%= link_to "Back to list", root_path %></p>

</section>